# https://github.com/resque/resque-scheduler/blob/master/README.md
#
# cron editor: http://www.corntab.com/pages/crontab-gui


###
# Every minute
#LogQueueMetrics:
#  cron: "* * * * *"
#  class: "TestClass"
#  queue: default

update_teams:
  # Everyday at 00:00
  cron: "0 0 * * *"
  class: "CrowdscoresUpdateTeams"
  queue: crowdscores_update_teams

update_competitions:
  # Everyday at 00:10
  cron: "10 0 * * *"
  class: "CrowdscoresUpdateCompetitions"
  queue: crowdscores_update_competitions

update_season:
  # Everyday at 00:20
  cron: "20 0 * * *"
  class: "CrowdscoresUpdateSeasons"
  queue: crowdscores_update_seasons

update_rounds:
  # Everyday at 00:30
  cron: "30 0 * * *"
  class: "CrowdscoresUpdateRounds"
  queue: crowdscores_update_rounds

update_teams:
  # Everyday at 00:40
  cron: "40 0 * * *"
  class: "CrowdscoresUpdateTeams"
  queue: crowdscores_update_teams

queue_match_updates:
  # Every 10 min
  cron: "0 */6 * * *"
  class: "MatchUpdatesQueuer"
  queue: match_updates_queuer
