# https://github.com/resque/resque-scheduler/blob/master/README.md
#
# cron editor: http://www.corntab.com/pages/crontab-gui


###
# Every minute
#LogQueueMetrics:
#  cron: "* * * * *"
#  class: "TestClass"
#  queue: default

update_teams:
  # Everyday at 01:40
  cron: "40 1 * * *"
  class: "CrowdscoresUpdateTeams"
  queue: crowdscores_update_teams

update_competitions:
  # Everyday at 01:40
  cron: "*/10 * * * *"
  class: "CrowdscoresUpdateCompetitions"
  queue: crowdscores_update_competitions

update_season:
    # Everyday at 01:45
    cron: "40 1 * * *"
    class: "CrowdscoresUpdateSeasons"
    queue: crowdscores_update_seasons

update_rounds:
  # Everyday at 01:50
  cron: "40 1 * * *"
  class: "CrowdscoresUpdateRounds"
  queue: crowdscores_update_rounds

update_teams:
  # Everyday at 01:55
  cron: "40 1 * * *"
  class: "CrowdscoresUpdateTeams"
  queue: crowdscores_update_teams

queue_match_updates:
  # Every 10 min
  cron: "*/10 * * * *"
  class: "MatchUpdatesQueuer"
  queue: match_updates_queuer
