# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffdb043a4298592d8e30d6a622d2a3e809dc3844ca705fc8303e481e81d86fff144201663a2b10fbb3b6a318c394839c08d9bec5e3be68b44796c5a9f2741e9a

test:
  secret_key_base: ed17af7266bb61b117e6e95a7d2dade8dab7464dbaf2db358fed64377301c6c78772b30afc52a106a1bd0f4963e42ead50e5ab056ff62362b71b4bb4360a1e16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
